<?php require_once 'templates/header.phtml'; ?>
</form><?php if($error) { ?>
    <div>
        <?= $error ?>
    </div>
<?php } ?>

<form action='login' method='post'>
    <label for='usuario'>Nombre de usuario</label>
    <input type='text' name='usuario' id="usuario" required>

    <label for='password'>Contraseña</label>
    <input type='password' name='password' id="password">

    <button type='submit'>Login</button>
</form>

<?php require "templates/footer.phtml"; ?>
