<?php require 'templates/header.phtml';   ?>     
 <?php require 'templates/form_alta.phtml'; ?>
 
 <ul class="list-group">
 
 <?php foreach($tasks as $task){ ?>
     
     <li class="list-group-item item-task  <?php if($task->finalizada) echo 'finalizada'?>">
         <div>
             <b><?php echo $task->titulo;?></b> | (Prioridad <?php echo $task->prioridad ?>)
         </div>
         <div class="actions">
         <a href="eliminar/<?php echo $task->id?>" type="button" class="btn btn-danger ml-auto">Borrar</a>
         <?php if(!$task->finalizada) {  ?><a href="finalizar/<?php echo $task->id?>" type="button" class="btn btn-success ml-auto">Finalizar</a><?php }?>
         </div>
     </li>
     
 <?php }?>
 </ul>
 <?php
 require 'templates/footer.phtml'; 